# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34b0e0b0ff40238f19874fa8b3e339c3fe643773fdc32551f3e5642e443e5da44c836e56c1989ebd8cb662220ffaca397b0dd7d678fbbe48d88f5aeed24e09ea

test:
  secret_key_base: da3c14f24b68cdefdc79d80a8275884363fba084197e70ca6fa1ccf71c96ecd0e7ee425102d142abe37e8c66635e9f6da26120cefcd2a9945f0b3d011b36e8ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
